-- BOARD TABLE SCRIPT FILE

DROP TABLE BOARD CASCADE CONSTRAINTS;

CREATE TABLE BOARD (
  BOARD_NUM NUMBER,             -- 게시글 번호
  BOARD_TITLE VARCHAR2(50),     -- 게시글 제목
  BOARD_WRITER VARCHAR2(15),    -- 게시글 작성장
  BOARD_CONTENT VARCHAR2(2000),    -- 게시글 내용
  BOARD_ORIGINAL_FILENAME VARCHAR2(100),  -- 업로드한 원래 파일명
  BOARD_RENAME_FILENAME VARCHAR2(100),  -- 바뀐 파일명
  BOARD_DATE DATE DEFAULT SYSDATE,  -- 게시글 올린 날짜
  BOARD_LEVEL NUMBER DEFAULT 0,   -- 글레벨 : 원글 0, 원글의 답글 1, 답글의 답글이면 2
  BOARD_REF NUMBER,  -- 원글일때는 자기번호, 답글일 때 참조하는 원글 번호
  BOARD_REPLY_REF NUMBER,    -- 레벨이 0이면 0, 레벨이 1이면 자기번호, 레벨이 2 이면 참조하는 답글번호
  BOARD_REPLY_SEQ NUMBER DEFAULT 0,   -- 답글의 순번
  BOARD_READ_COUNT NUMBER DEFAULT 0,   -- 조회수
  
  CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NUM),
  CONSTRAINT PK_BOARD_WRITER FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER (ID) ON DELETE SET NULL,
  CONSTRAINT FK_BOARD_REF FOREIGN KEY (BOARD_REF) REFERENCES BOARD (BOARD_NUM) ON DELETE CASCADE,
  CONSTRAINT FK_BOARD_REPLY_REF FOREIGN KEY (BOARD_REPLY_REF) REFERENCES BOARD (BOARD_NUM) ON DELETE CASCADE
);

COMMENT ON COLUMN BOARD.BOARD_NUM IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '게시글작성자 아이디';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOARD_DATE IS '게시글올린날짜';
COMMENT ON COLUMN BOARD.BOARD_ORIGINAL_FILENAME IS '게시글변경전이름';
COMMENT ON COLUMN BOARD.BOARD_RENAME_FILENAME IS '게시글변경후이름';
COMMENT ON COLUMN BOARD.BOARD_LEVEL IS '게시글레벨';
COMMENT ON COLUMN BOARD.BOARD_REPLY_REF IS '답글참조';
COMMENT ON COLUMN BOARD.BOARD_REPLY_SEQ IS '게시글순번';
COMMENT ON COLUMN BOARD.BOARD_READ_COUNT IS '조회수';

INSERT INTO BOARD VALUES (1, '관리자 게시글', 'admin', '저희 사이트를 이용해 주셔서 감사합니다.', NULL, NULL, SYSDATE,
0, 1, NULL, 0, 0);

INSERT INTO BOARD VALUES (2, 'MVC Model2 패턴이란', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 2, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (3, 'MVC Model1 패턴이란', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 3, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (4, 'MVC', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 4, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (5, 'MVC마이탐', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 5, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (6, 'MVC 붓싼', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 6, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (7, '정상수', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 7, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (8, '랩퇴물', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 8, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (9, '원투쓰리', 'user22', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 9, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (10, 'MINUS', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 10, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (11, '봉봉', 'user22', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 11, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (12, '쭉쭉쭉', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 12, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (13, '쭉쭉쭉1', 'user22', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 13, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (14, '쭉쭉쭉2', 'user11', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 14, NULL, DEFAULT, DEFAULT);

INSERT INTO BOARD VALUES (15, '쭉쭉쭉3', 'user22', '웹 애플리케이션 설계 방식중 하나입니다.', NULL, NULL, DEFAULT,
DEFAULT, 15, NULL, DEFAULT, DEFAULT);


COMMIT;

