DROP TABLE NOTICE CASCADE CONSTRAINTS;

CREATE TABLE NOTICE (
	NOTICE_NO NUMBER,
	NOTICE_TITLE VARCHAR2(30) NOT NULL,
	NOTICE_WRITER VARCHAR2(15) NOT NULL,
	NOTICE_DATE DATE DEFAULT SYSDATE,
	NOTICE_CONTENT VARCHAR2(2000),
	FILE_PATH VARCHAR2(100),
	
	CONSTRAINT PK_NOTICENO PRIMARY KEY(NOTICE_NO),
	CONSTRAINT FK_NWRITER FOREIGN KEY (NOTICE_WRITER) REFERENCES MEMBER (ID)
);


INSERT INTO NOTICE VALUES (
	1, '관리자 공지사항', 'admin', TO_DATE('2017-01-05', 'RRRR-MM-DD'), '공지서비스를 개시합니다. 많이 이용해 주세요.', NULL 
);

INSERT INTO NOTICE VALUES (
	2, '테스트 공지사항', 'user11', TO_DATE('2017-04-05', 'RRRR-MM-DD'), '공지테스트 원투스리.', NULL 
);

INSERT INTO NOTICE VALUES (
	1, '메탈슬러그3', 'user22', TO_DATE('2017-01-05', 'RRRR-MM-DD'), '오늘은 깨고말겠다. 좀비로.', NULL 
);

COMMIT;

